import * as REST from 'discord-api-types/rest';
import { group, route, type } from '../route-group';
import { Routes } from 'discord-api-types/rest';

/** Routes on https://discord.com/developers/docs/resources/channel. */
export const channel = group({
  // getChannel,
  // modifyChannel,
  // deleteChannel,
  // getChannelMessages,
  // getChannelMessage,
  // createMessage,
  // crosspostMessage,
  // createReaction,
  // deleteOwnReaction,
  // deleteUserReacion,
  // getReactions,
  // deleteAllReactions,
  // deleteAllReactionsForEmoji,
  // editMessage,
  // deleteMessage,
  // bulkDeleteMessages,
  // editChannelPermissions,
  // getChannelInvites,
  // createChannelInvite,
  // deleteChannelPermission,
  // followNewsChannel,
  // triggerTypingIndicator,
  // getPinnedMessages,
  // pinMessag,
  // unpinMessage,
  // groupDMAddRecipient,
  // groupDMRemoveRecipient,
  // startThreadFromMessage,
  // startThreadWithoutMessage,
  // startThreadInForumChannel,
  // joinThread,
  // addThreadMember,
  // leaveThread,
  // removeThreadMember,
  // getThreadMember,
  // listThreadMembers,
  // listPublicArchivedThreads,
  // listPrivateArchivedThreads,
  // listJoinedPrivateArchivedThreads
});
